#ifndef CAMERAMANIPULATORWIDGET_GLOBAL_H
#define CAMERAMANIPULATORWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAMERAMANIPULATORWIDGET_LIBRARY)
#  define CAMERAMANIPULATORWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define CAMERAMANIPULATORWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERAMANIPULATORWIDGET_GLOBAL_H
