
foo: foo.cpp MyPlaceNode.h MyPlaceNode.cpp
	g++ -std=c++11 -o foo foo.cpp MyPlaceNode.cpp -losg -losgViewer -losgEarth -losgEarthUtil -losgDB -lOpenThreads -losgText -losgEarthAnnotation -losgEarthSymbology -losgEarthFeatures
