#ifndef CAMPASSWIDGET_GLOBAL_H
#define CAMPASSWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAMPASSWIDGET_LIBRARY)
#  define CAMPASSWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define CAMPASSWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMPASSWIDGET_GLOBAL_H
